commands-help-name = help
commands-help-description = Get help
commands-start-name = start
commands-start-description = Setup Cerebro
commands-ping-name = ping
commands-ping-description = Ping the bot
commands-subscription-name = subscription
commands-subscription-description = Fund Subscription
commands-referral-name = referral
commands-referral-description = Get your referral code
commands-kolcode-name = kolcode
commands-kolcode-description = Set a KOL code
commands-githubcheck-name = githubcheck
commands-githubcheck-description = Check a GitHubs authenticity
commands-githubdetailed-name = githubdetailed
commands-githubdetailed-description = Check a GitHubs authenticity
commands-dex-name = dex
commands-dex-description = Check dex has been paid
commands-socials-name = socials
commands-socials-description = Find token socials
commands-bundle-name = bundle
commands-bundle-description = Check if a token was bundled
commands-heatmap-name = heatmap
commands-heatmap-description = Cryptocurrency prices on a visually appealing heatmap
commands-webca-name = webca
commands-webca-description = Start a tracker to watch for ca deploys
