commands-help-name = ayuda
commands-help-description = Consige ayuda
commands-start-name = comenzar
commands-start-description = Configurar Cerebro
commands-ping-name = ping
commands-ping-description = Ping al bot
commands-subscription-name = suscripción
commands-subscription-description = Pagar suscripción
commands-referral-name = referencia
commands-referral-description = Ten tu código de referencia
commands-kolcode-name = códigodekol
commands-kolcode-description = Ten un código KOL
commands-githubcheck-name = revisargithub
commands-githubcheck-description = Revisar la autenticidad de un github
commands-githubdetailed-name = githubdetallado
commands-githubdetailed-description = Revisar la autenticidad de un github
commands-dex-name = dex
commands-dex-description = Revisar si el Dex ha sido pagado
commands-socials-name = sociales
commands-socials-description = Encuentra los enlaces sociales del token
commands-bundle-name = bundle
commands-bundle-description = Revisar si un token ha tenido bundle
commands-heatmap-name = heatmap
commands-heatmap-description = Precios visualizados de las principales criptomonedas, heatmap
commands-webca-name = webca
commands-webca-description = Iniciar un seguimiento para ver despliegue de contratos
