commands-help-name = Ayuda
commands-help-description = Consige ayuda
commands-start-name = Comenzar
commands-start-description = Configurar Cerebro
commands-ping-name = ping
commands-ping-description = Ping al bot
commands-subscription-name = Suscripción
commands-subscription-description = Pagar suscripción
commands-referral-name = Referencia
commands-referral-description = Ten tu código de referencia
commands-kolcode-name = Código de KOL
commands-kolcode-description = Ten un código KOL
commands-githubcheck-name = Revisar github
commands-githubcheck-description = Revisar la autenticidad de un github
commands-githubdetailed-name = Github detallado
commands-githubdetailed-description = Revisar la autenticidad de un github
commands-dex-name = Dex
commands-dex-description = Revisar si el Dex ha sido pagado
commands-socials-name = Links sociales
commands-socials-description = Encuentra los enlaces sociales del token
commands-bundle-name = bundle
commands-bundle-description = Revisar si un token ha tenido bundle
commands-heatmap-name = heatmap
commands-heatmap-description = Precios visualizados de las principales criptomonedas, heatmap
commands-webca-name = Web CA
commands-webca-description = Iniciar un seguimiento para ver despliegue de contratos
