commands-help-name = ajuda
commands-help-description = obter ajuda
commands-start-name = iniciar
commands-start-description = iniciar cerebro
commands-ping-name = pingar
commands-ping-description = Pingar o bot
commands-subscription-name = assinatura
commands-subscription-description = adicionar fundos
commands-referral-name = referencia
commands-referral-description = obtenha seu código de referência
commands-kolcode-name = codigokol
commands-kolcode-description = obter seu código KOL
commands-githubcheck-name = verificacaodogithub
commands-githubcheck-description = checar a autenticidade de um github
commands-githubdetailed-name = githubdetalhado
commands-githubdetailed-description = checar a autenticidade de um github
commands-dex-name = dex
commands-dex-description = checar se a dex foi paga
commands-socials-name = sociais
commands-socials-description = encontrar as redes sociais de um token
commands-bundle-name = bundle
commands-bundle-description = checar se um token sofreu um bundle
commands-heatmap-name = heatmap
commands-heatmap-description = preço de uma criptomoeda em forma de heatmap
commands-webca-name = webca
commands-webca-description = Trackear uma página para procurar por contratos recém adicionados
commands-tax-name = imposto
commands-tax-description = Verifique se um token tem imposto
