commands-help-name = aide
commands-help-description = Obtenir de l'aide
commands-start-name = commencer
commands-start-description = Configurer Cerebro
commands-ping-name = ping
commands-ping-description = Envoyez un ping au bot
commands-subscription-name = abonnement
commands-subscription-description = Souscription au fonds
commands-referral-name = reference
commands-referral-description = Obtenez votre code de parrainage
commands-kolcode-name = kolcode
commands-kolcode-description = Définir un code KOL
commands-githubcheck-name = githubverifier
commands-githubcheck-description = Vérifiez l'authenticité d'un GitHubs
commands-githubdetailed-name = githubdetaille
commands-githubdetailed-description = Vérifiez l'authenticité d'un GitHubs
commands-dex-name = dex
commands-dex-description = Vérifiez que dex a été payé
commands-socials-name = socials
commands-socials-description = Trouver des tokens sociaux
commands-bundle-name = bundle
commands-bundle-description = Vérifiez si un jeton a été bundled
commands-heatmap-name = cartethermique
commands-heatmap-description = Les prix des crypto-monnaies sur une carte thermique visuellement attrayante
commands-webca-name = webca
commands-webca-description = Démarrer un outil de suivi pour surveiller les déploiements de CA
commands-tax-name = impôt
commands-tax-description = Vérifiez si un jeton a une taxe
